version: '3.4'

services:
  gatewayformicroservices:
    image: ${DOCKER_REGISTRY-}gatewayformicroservices
    build:
      context: .
      dockerfile: GatewayForMicroservices/Dockerfile
  
  microservicesproject1:
    image: ${DOCKER_REGISTRY-}microservicesproject1
    build:
      context: .
      dockerfile: MicroservicesProject1/Dockerfile

  microservicesproject2:
    image: ${DOCKER_REGISTRY-}microservicesproject2
    build:
      context: .
      dockerfile: MicroservicesProject2/Dockerfile

